{% set name = "azure-purview-nspkg" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-purview-nspkg-{{ version }}.zip
  sha256: 1a3d9ff1ee481cab9d2ac96616b1370a6665175d86f22a298dd91fa8472e0199

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - azure-nspkg >=2.0.0

test:
  imports:
    - azure.purview
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Purview Namespace Package
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - redur
